@ECHO OFF
SET TESTER=C:\Shared\MidaxTester\MidaxTester.exe
start PsExec -accepteula \\WEBSERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-01
start PsExec -accepteula \\WEBSERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-02
start PsExec -accepteula \\WEBSERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-03
start PsExec -accepteula \\WEBSERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-04
start PsExec -accepteula \\WEBSERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-05
start PsExec -accepteula \\WEBSERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-06
start PsExec -accepteula \\WEBSERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-07
start PsExec -accepteula \\WEBSERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-08
start PsExec -accepteula \\WEBSERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-09
start PsExec -accepteula \\WEBSERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-10
start PsExec -accepteula \\COMPUTESERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-11
start PsExec -accepteula \\COMPUTESERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-12
start PsExec -accepteula \\COMPUTESERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-13
start PsExec -accepteula \\COMPUTESERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-14
start PsExec -accepteula \\COMPUTESERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-15
start PsExec -accepteula \\COMPUTESERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-16
start PsExec -accepteula \\COMPUTESERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-17
start PsExec -accepteula \\COMPUTESERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-18
start PsExec -accepteula \\COMPUTESERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-19
start PsExec -accepteula \\COMPUTESERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-20
start PsExec -accepteula \\COMPUTESERV1 %TESTER% -G -FROMDB -TODB -%2 -%1-21
start PsExec -accepteula \\COMPUTESERV2 %TESTER% -G -FROMDB -TODB -%2 -%1-22
start PsExec -accepteula \\COMPUTESERV2 %TESTER% -G -FROMDB -TODB -%2 -%1-23
start PsExec -accepteula \\COMPUTESERV2 %TESTER% -G -FROMDB -TODB -%2 -%1-24
start PsExec -accepteula \\COMPUTESERV2 %TESTER% -G -FROMDB -TODB -%2 -%1-25
start PsExec -accepteula \\COMPUTESERV2 %TESTER% -G -FROMDB -TODB -%2 -%1-26
start PsExec -accepteula \\COMPUTESERV2 %TESTER% -G -FROMDB -TODB -%2 -%1-27
start PsExec -accepteula \\COMPUTESERV2 %TESTER% -G -FROMDB -TODB -%2 -%1-28
start PsExec -accepteula \\COMPUTESERV2 %TESTER% -G -FROMDB -TODB -%2 -%1-29
start PsExec -accepteula \\COMPUTESERV2 %TESTER% -G -FROMDB -TODB -%2 -%1-30
start PsExec -accepteula \\COMPUTESERV2 %TESTER% -G -FROMDB -TODB -%2 -%1-31