//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midax.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public string PORT_INPUT {
            get {
                return ((string)(this["PORT_INPUT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Midax")]
        public string APP_NAME {
            get {
                return ((string)(this["APP_NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8d341413c2eae2c35bb5b47a594ef08ae18cb3b7")]
        public string API_KEY {
            get {
                return ((string)(this["API_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ksbitlsoftdemo")]
        public string USER_NAME {
            get {
                return ((string)(this["USER_NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kotik0483")]
        public string PASSWORD {
            get {
                return ((string)(this["PASSWORD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAX:IX.D.DAX.DAILY.IP")]
        public string INDEX {
            get {
                return ((string)(this["INDEX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FUTURE {
            get {
                return ((string)(this["FUTURE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Adidas AG:ED.D.ADSGY.DAILY.IP</string>\r\n  <string>Allianz SE:ED.D.ALVGY.DA" +
            "ILY.IP</string>\r\n  <string>BASF SE:ED.D.BAS.DAILY.IP</string>\r\n  <string>Bayer A" +
            "G:ED.D.BAY.DAILY.IP</string>\r\n  <string>Bayerische Motoren Werke AG:ED.D.BMW.DAI" +
            "LY.IP</string>\r\n  <string>Beiersdorf AG:ED.D.BEI.DAILY.IP</string>\r\n  <string>Co" +
            "mmerzbank AG:ED.D.CBK.DAILY.IP</string>\r\n  <string>Continental AG:ED.D.CON.DAILY" +
            ".IP</string>\r\n  <string>Daimler AG:ED.D.DCX.DAILY.IP</string>\r\n  <string>Deutsch" +
            "e Bank AG:ED.D.DBK.DAILY.IP</string>\r\n  <string>Deutsche Boerse AG:ED.D.DB1.DAIL" +
            "Y.IP</string>\r\n  <string>Deutsche Lufthansa AG:ED.D.LHAG.DAILY.IP</string>\r\n  <s" +
            "tring>Deutsche Post AG:ED.D.DPW.DAILY.IP</string>\r\n  <string>Deutsche Telekom AG" +
            ":ED.D.DTE.DAILY.IP</string>\r\n  <string>E.ON SE:ED.D.EOA.DAILY.IP</string>\r\n  <st" +
            "ring>Fresenius Medical Care AG:ED.D.FME.DAILY.IP</string>\r\n  <string>HeidelbergC" +
            "ement AG:ED.D.HEI.DAILY.IP</string>\r\n  <string>Henkel AG:ED.D.HENGY.DAILY.IP</st" +
            "ring>\r\n  <string>Infineon Technologies AG:ED.D.IFX.DAILY.IP</string>\r\n  <string>" +
            "K+S AG:ED.D.SDF.DAILY.IP</string>\r\n  <string>LANXESS AG:ED.D.LXS.DAILY.IP</strin" +
            "g>\r\n  <string>Linde AG:ED.D.LING.DAILY.IP</string>\r\n  <string>Merck KGaA:ED.D.MR" +
            "CG.DAILY.IP</string>\r\n  <string>Muenchener Rueckversicherungs AG:ED.D.MUV2.DAILY" +
            ".IP</string>\r\n  <string>RWE AG:ED.D.RWEG.DAILY.IP</string>\r\n  <string>SAP AG:ED." +
            "D.SAPG.DAILY.IP</string>\r\n  <string>Siemens AG:ED.D.SIEGn.DAILY.IP</string>\r\n  <" +
            "string>ThyssenKrupp AG:ED.D.TKAG.DAILY.IP</string>\r\n  <string>Volkswagen AG:ED.D" +
            ".VOW.DAILY.IP</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection STOCKS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["STOCKS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MIDAX")]
        public string MODEL {
            get {
                return ((string)(this["MODEL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string TRADING_LIMIT_PER_BP {
            get {
                return ((string)(this["TRADING_LIMIT_PER_BP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06:00:00")]
        public string PUBLISHING_START_TIME {
            get {
                return ((string)(this["PUBLISHING_START_TIME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("07:00:00")]
        public string TRADING_START_TIME {
            get {
                return ((string)(this["TRADING_START_TIME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17:00:00")]
        public string TRADING_STOP_TIME {
            get {
                return ((string)(this["TRADING_STOP_TIME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRODUCTION")]
        public string TRADING_MODE {
            get {
                return ((string)(this["TRADING_MODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18:00:00")]
        public string PUBLISHING_STOP_TIME {
            get {
                return ((string)(this["PUBLISHING_STOP_TIME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.26")]
        public string DB_CONTACTPOINT {
            get {
                return ((string)(this["DB_CONTACTPOINT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IN.D.VIX.MONTH2.IP")]
        public string VOLATILITY_2M {
            get {
                return ((string)(this["VOLATILITY_2M"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IN.D.VIX.MONTH3.IP")]
        public string VOLATILITY_3M {
            get {
                return ((string)(this["VOLATILITY_3M"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GBP")]
        public string TRADING_CURRENCY {
            get {
                return ((string)(this["TRADING_CURRENCY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16:00:00")]
        public string TRADING_CLOSING_TIME {
            get {
                return ((string)(this["TRADING_CLOSING_TIME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16:55:00")]
        public string FORCE_CLOSE_POSITIONS_TIME {
            get {
                return ((string)(this["FORCE_CLOSE_POSITIONS_TIME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MacD_10_60_IX.D.DAX.DAILY.IP")]
        public string TRADING_SIGNAL {
            get {
                return ((string)(this["TRADING_SIGNAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21:00:00")]
        public string PUBLISHING_MARKET_LEVELS_TIME {
            get {
                return ((string)(this["PUBLISHING_MARKET_LEVELS_TIME"]));
            }
        }
    }
}
